version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
     - "8090:8090"
    container_name: app
    links: 
      - redis:redis
      - mongodb:mongodb
    depends_on: 
      - redis
      - mongodb